
#################
# 
# This script loads the SEM tables generated by fit_obspi.R and plots results
# NOTE: this script should be run from within each current_models dir
#
#################

source("~/Data/bgs_lmr/human_data/tools/HelperFunctions.R")

constrained_models <- c("split_cds_phastcons", "split_cds_regulatory")
mutation_maps <- c("carlson", "gnomad", "roulette")

#################
#
# Simple correlations (latent constructs for B, mu, r)
#
#################

# 10kb
pearson_10kb_models <- list(length=2)
for(i in 1:length(constrained_models)) {
  
  m <- constrained_models[i]
  pearson_10kb <- list(length=num_chrom)
  
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/pearson_chr", c, "_", m, "_10kb.csv", sep=""))
    var_names <- setdiff(names(tmp), "V1")
    
    long <- tmp %>%
      pivot_longer(
        cols = -V1,
        names_to = "variable2",
        values_to = "value"
      ) %>%
      dplyr::rename(variable1 = V1) %>%
      filter(variable1 != variable2) %>%
      mutate(
        i = match(variable1, var_names),  
        j = match(variable2, var_names), 
        pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
      )
    
    # lower triangle: correlations
    corr_long <- long %>%
      filter(i > j, !is.na(value)) %>%
      transmute(
        pair_key,
        var1 = pmin(variable1, variable2),
        var2 = pmax(variable1, variable2),
        correlation = as.numeric(value)
      )
    
    # upper triangle: p-values
    pval_long <- long %>%
      filter(i < j, !is.na(value)) %>%
      transmute(
        pair_key,
        pvalue = as.numeric(value)
      )
    
    flat_matrix <- corr_long %>%
      left_join(pval_long, by = "pair_key") %>%
      arrange(., var1, var2)
    
    flat_matrix$chrom <- c
    pearson_10kb[[c]] <- flat_matrix
  }
  
  pearson_10kb <- do.call(rbind.data.frame, pearson_10kb)
  pearson_10kb$constrained_model <- m
  
  pearson_10kb_models[[i]] <- pearson_10kb
}

pearson_10kb_models <- data.table::rbindlist(pearson_10kb_models)
pearson_10kb_models$scale <- 1e+4

# 100kb
pearson_100kb_models <- list(length=2)
for(i in 1:length(constrained_models)) {
  
  m <- constrained_models[i]
  pearson_100kb <- list(length=num_chrom)
  
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/pearson_chr", c, "_", m, "_100kb.csv", sep=""))
    
    var_names <- setdiff(names(tmp), "V1")
    
    long <- tmp %>%
      pivot_longer(
        cols = -V1,
        names_to = "variable2",
        values_to = "value"
      ) %>%
      dplyr::rename(variable1 = V1) %>%
      filter(variable1 != variable2) %>%
      mutate(
        i = match(variable1, var_names),  
        j = match(variable2, var_names), 
        pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
      )
    
    # lower triangle: correlations
    corr_long <- long %>%
      filter(i > j, !is.na(value)) %>%
      transmute(
        pair_key,
        var1 = pmin(variable1, variable2),
        var2 = pmax(variable1, variable2),
        correlation = as.numeric(value)
      )
    
    # upper triangle: p-values
    pval_long <- long %>%
      filter(i < j, !is.na(value)) %>%
      transmute(
        pair_key,
        pvalue = as.numeric(value)
      )
    
    flat_matrix <- corr_long %>%
      left_join(pval_long, by = "pair_key") %>%
      arrange(., var1, var2)
    
    flat_matrix$chrom <- c
    pearson_100kb[[c]] <- flat_matrix
  }
  
  pearson_100kb <- do.call(rbind.data.frame, pearson_100kb)
  pearson_100kb$constrained_model <- m
  
  pearson_100kb_models[[i]] <- pearson_100kb
}

pearson_100kb_models <- data.table::rbindlist(pearson_100kb_models)
pearson_100kb_models$scale <- 1e+5

# 1Mb
pearson_1Mb_models <- list(length=2)
for(i in 1:length(constrained_models)) {
  
  m <- constrained_models[i]
  pearson_1Mb <- list(length=num_chrom)
  
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/pearson_chr", c, "_", m, "_1Mb.csv", sep=""))
    
    var_names <- setdiff(names(tmp), "V1")
    
    long <- tmp %>%
      pivot_longer(
        cols = -V1,
        names_to = "variable2",
        values_to = "value"
      ) %>%
      dplyr::rename(variable1 = V1) %>%
      filter(variable1 != variable2) %>%
      mutate(
        i = match(variable1, var_names), 
        j = match(variable2, var_names),
        pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
      )
    
    # lower triangle: correlations
    corr_long <- long %>%
      filter(i > j, !is.na(value)) %>%
      transmute(
        pair_key,
        var1 = pmin(variable1, variable2),
        var2 = pmax(variable1, variable2),
        correlation = as.numeric(value)
      )
    
    # upper triangle: p-values
    pval_long <- long %>%
      filter(i < j, !is.na(value)) %>%
      transmute(
        pair_key,
        pvalue = as.numeric(value)
      )
    
    flat_matrix <- corr_long %>%
      left_join(pval_long, by = "pair_key") %>%
      arrange(., var1, var2)
    
    flat_matrix$chrom <- c
    pearson_1Mb[[c]] <- flat_matrix
  }
  
  pearson_1Mb <- do.call(rbind.data.frame, pearson_1Mb)
  pearson_1Mb$constrained_model <- m
  
  pearson_1Mb_models[[i]] <- pearson_1Mb
}

pearson_1Mb_models <- data.table::rbindlist(pearson_1Mb_models)
pearson_1Mb_models$scale <- 1e+6

pearson_cors <- rbind.data.frame(pearson_10kb_models, pearson_100kb_models, pearson_1Mb_models) 

pearson_cors$constrained_model <- factor(pearson_cors$constrained_model,
                                         levels = names(elem_labels), 
                                         labels = unname(elem_labels))

for(var in unique(c(pearson_cors$var1, pearson_cors$var2))) {
  
  tbl <- pearson_cors %>% filter(., var1 == var | var2 == var) %>%
    mutate(v1 = var1, v2 = var2,                  
           var1 = if_else(v2 == var, v2, v1),            
           var2 = if_else(v2 == var, v1, v2)) %>% dplyr::select(-v1, -v2)
  
  tbl$sig <- tbl$pvalue < 0.05 / num_chrom
  
  p <- ggplot(data=tbl, aes(x=chrom, y=correlation, alpha=sig, color=var2)) +
    geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
    facet_grid(scale/1e3~constrained_model) + theme_classic() + 
    scale_y_continuous(breaks=pretty_breaks()) +
    scale_x_continuous(breaks=1:num_chrom) + 
    scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                       labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
    scale_color_manual(values=c("brown1", "cyan3", "purple3", "gold3"),
                       labels=c(B="B",
                                avg_mut=expression(mu),
                                avg_pi=expression(pi),
                                avg_rec="r",
                                prop_del_sites="E"),
                       name=NULL) +
    labs(title=NULL, x="Chromosome", y="Pearson correlation") +
    theme(strip.text.y=element_text(size=16),     
          strip.text.x=element_text(size=16),    
          axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.title=element_text(size=16),
          legend.position="bottom")
  save_plot(paste("sem/pearson_", var, ".pdf", sep=""), p, base_height=7, base_width=16)
}

#################
#
# Correlations with raw mutation maps instead of latent
#
#################

## reload
human_maps_10kb <- fread("maps/maps_10kb.csv.gz")
human_maps_100kb <- fread("maps/maps_100kb.csv.gz") 
human_maps_1Mb <- fread("maps/maps_1Mb.csv.gz")

# 10kb
pearson_10kb <- list(length=length(mutation_maps) * length(constrained_models) * num_chrom)
idx <- 1
for(u in mutation_maps) {
  for(m in constrained_models) {
    for(c in 1:num_chrom) {
      
      data <- filter(human_maps_10kb, mut_map==u, constrained_model==m, chrom==c, coverage >= 0.75) %>%
        dplyr::select(., avg_pi, prop_del_sites, B, avg_rec, avg_mut)
      n <- ncol(data)
      
      cor_mat <- matrix(NA, n, n)
      p_mat <- matrix(NA, n, n)
      colnames(cor_mat) <- rownames(cor_mat) <- colnames(data)
      colnames(p_mat) <- rownames(p_mat) <- colnames(data)
      
      for (i in 1:n) {
        for (j in 1:n) {
          test <- cor.test(data[[i]], data[[j]], method = "pearson", use = "complete.obs")
          cor_mat[i, j] <- test$estimate
          p_mat[i, j] <- test$p.value
        }
      }
      
      combined_mat <- matrix(NA_real_, n, n)
      for (i in 1:n) {
        for (j in 1:n) {
          if (i > j) {
            combined_mat[i, j] <- round(cor_mat[i, j], 4)
          } else if (i < j) {
            combined_mat[i, j] <- signif(p_mat[i, j], 3)
          }
        }
      }
      
      combined_mat <- setDT(as.data.frame(combined_mat))
      rownames(combined_mat) <- colnames(combined_mat) <- colnames(data)
      
      var_names <- names(combined_mat)
      combined_mat$V1 <- rownames(combined_mat)
      
      long <- combined_mat %>%
        pivot_longer(
          cols = -V1,
          names_to = "variable2",
          values_to = "value"
        ) %>%
        dplyr::rename(variable1 = V1) %>%
        filter(variable1 != variable2) %>%
        mutate(
          i = match(variable1, var_names), 
          j = match(variable2, var_names),  
          pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
        )
      
      corr_long <- long %>%
        filter(i > j, !is.na(value)) %>%
        transmute(
          pair_key,
          var1 = pmin(variable1, variable2),
          var2 = pmax(variable1, variable2),
          correlation = as.numeric(value)
        )
      
      pval_long <- long %>%
        filter(i < j, !is.na(value)) %>%
        transmute(
          pair_key,
          pvalue = as.numeric(value)
        )
      
      flat_matrix <- corr_long %>%
        left_join(pval_long, by = "pair_key") %>%
        arrange(., var1, var2)
      
      flat_matrix$chrom <- c
      flat_matrix$constrained_model <- m
      flat_matrix$mut_map <- u
      
      pearson_10kb[[idx]] <- flat_matrix
      idx <- idx + 1
    }
  }
}

pearson_10kb <- data.table::rbindlist(pearson_10kb)
pearson_10kb$scale <- 1e+4

# 100kb
pearson_100kb <- list(length=length(mutation_maps) * length(constrained_models) * num_chrom)
idx <- 1
for(u in mutation_maps) {
  for(m in constrained_models) {
    for(c in 1:num_chrom) {
      
      data <- filter(human_maps_100kb, mut_map==u, constrained_model==m, chrom==c, coverage >= 0.5) %>%
        dplyr::select(., avg_pi, prop_del_sites, B, avg_rec, avg_mut)
      n <- ncol(data)
      
      cor_mat <- matrix(NA, n, n)
      p_mat <- matrix(NA, n, n)
      colnames(cor_mat) <- rownames(cor_mat) <- colnames(data)
      colnames(p_mat) <- rownames(p_mat) <- colnames(data)
      
      for(i in 1:n) {
        for(j in 1:n) {
          test <- cor.test(data[[i]], data[[j]], method = "pearson", use = "complete.obs")
          cor_mat[i, j] <- test$estimate
          p_mat[i, j] <- test$p.value
        }
      }
      
      combined_mat <- matrix(NA_real_, n, n)
      for (i in 1:n) {
        for (j in 1:n) {
          if (i > j) {
            combined_mat[i, j] <- round(cor_mat[i, j], 4)
          } else if (i < j) {
            combined_mat[i, j] <- signif(p_mat[i, j], 3)
          }
        }
      }
      
      combined_mat <- setDT(as.data.frame(combined_mat))
      rownames(combined_mat) <- colnames(combined_mat) <- colnames(data)
      
      var_names <- names(combined_mat)
      combined_mat$V1 <- rownames(combined_mat)
      
      long <- combined_mat %>%
        pivot_longer(
          cols = -V1,
          names_to = "variable2",
          values_to = "value"
        ) %>%
        dplyr::rename(variable1 = V1) %>%
        filter(variable1 != variable2) %>%
        mutate(
          i = match(variable1, var_names), 
          j = match(variable2, var_names),  
          pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
        )
      
      corr_long <- long %>%
        filter(i > j, !is.na(value)) %>%
        transmute(
          pair_key,
          var1 = pmin(variable1, variable2),
          var2 = pmax(variable1, variable2),
          correlation = as.numeric(value)
        )
      
      pval_long <- long %>%
        filter(i < j, !is.na(value)) %>%
        transmute(
          pair_key,
          pvalue = as.numeric(value)
        )
      
      flat_matrix <- corr_long %>%
        left_join(pval_long, by = "pair_key") %>%
        arrange(., var1, var2)
      
      flat_matrix$chrom <- c
      flat_matrix$constrained_model <- m
      flat_matrix$mut_map <- u
      
      pearson_100kb[[idx]] <- flat_matrix
      idx <- idx + 1
    }
  }
}

pearson_100kb <- do.call(rbind.data.frame, pearson_100kb)
pearson_100kb$scale <- 1e+5

# 1Mb
pearson_1Mb <- list(length=length(mutation_maps) * length(constrained_models) * num_chrom)
idx <- 1
for(u in mutation_maps) {
  for(m in constrained_models) {
    for(c in 1:num_chrom) {
      
      data <- filter(human_maps_1Mb, mut_map==u, constrained_model==m, chrom==c, coverage >= 0.25) %>%
        dplyr::select(., avg_pi, prop_del_sites, B, avg_rec, avg_mut)
      n <- ncol(data)
      
      cor_mat <- matrix(NA, n, n)
      p_mat <- matrix(NA, n, n)
      colnames(cor_mat) <- rownames(cor_mat) <- colnames(data)
      colnames(p_mat) <- rownames(p_mat) <- colnames(data)
      
      for(i in 1:n) {
        for(j in 1:n) {
          test <- cor.test(data[[i]], data[[j]], method = "pearson", use = "complete.obs")
          cor_mat[i, j] <- test$estimate
          p_mat[i, j] <- test$p.value
        }
      }
      
      combined_mat <- matrix(NA_real_, n, n)
      for (i in 1:n) {
        for (j in 1:n) {
          if (i > j) {
            combined_mat[i, j] <- round(cor_mat[i, j], 4)
          } else if (i < j) {
            combined_mat[i, j] <- signif(p_mat[i, j], 3)
          }
        }
      }
      
      combined_mat <- setDT(as.data.frame(combined_mat))
      rownames(combined_mat) <- colnames(combined_mat) <- colnames(data)
      
      var_names <- names(combined_mat)
      combined_mat$V1 <- rownames(combined_mat)
      
      long <- combined_mat %>%
        pivot_longer(
          cols = -V1,
          names_to = "variable2",
          values_to = "value"
        ) %>%
        dplyr::rename(variable1 = V1) %>%
        filter(variable1 != variable2) %>%
        mutate(
          i = match(variable1, var_names),  
          j = match(variable2, var_names),  
          pair_key = paste(pmin(variable1, variable2), pmax(variable1, variable2), sep = "|")
        )
      
      corr_long <- long %>%
        filter(i > j, !is.na(value)) %>%
        transmute(
          pair_key,
          var1 = pmin(variable1, variable2),
          var2 = pmax(variable1, variable2),
          correlation = as.numeric(value)
        )
      
      pval_long <- long %>%
        filter(i < j, !is.na(value)) %>%
        transmute(
          pair_key,
          pvalue = as.numeric(value)
        )
      
      flat_matrix <- corr_long %>%
        left_join(pval_long, by = "pair_key") %>%
        arrange(., var1, var2)
      
      flat_matrix$chrom <- c
      flat_matrix$constrained_model <- m
      flat_matrix$mut_map <- u
      
      pearson_1Mb[[idx]] <- flat_matrix
      idx <- idx + 1
    }
  }
}

pearson_1Mb <- data.table::rbindlist(pearson_1Mb)
pearson_1Mb$scale <- 1e+6

pearson_raw_muts <- rbind.data.frame(pearson_10kb, pearson_100kb, pearson_1Mb)

tbl <- pearson_raw_muts %>% filter(., var1 == "avg_mut" | var2 == "avg_mut") %>%
  mutate(v1 = var1, v2 = var2,                  
         var1 = if_else(v2 == "avg_mut", v2, v1),            
         var2 = if_else(v2 == "avg_mut", v1, v2)             
  ) %>% dplyr::select(-v1, -v2) 

tbl$constrained_model <- factor(tbl$constrained_model,
                                levels = names(elem_labels), 
                                labels = unname(elem_labels))

for(scal in unique(tbl$scale)) {
  p <- ggplot(data=filter(tbl, pvalue < 0.05 / num_chrom, scale==scal),
              aes(x=chrom, 
                  y=correlation, 
                  color=var2)) +
    geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
    facet_grid(mut_map~constrained_model) + theme_classic() + 
    scale_y_continuous(breaks=pretty_breaks()) +
    scale_x_continuous(breaks=1:num_chrom) + 
    scale_color_manual(values=c("brown1", "cyan3", "purple3", "gold3"),
                       labels=c(B="B",
                                avg_mut=expression(mu),
                                avg_pi=expression(pi),
                                avg_rec="r",
                                prop_del_sites="E"),
                       name=NULL) +
    labs(title=NULL, x="Chromosome", y="Pearson correlation") +
    theme(strip.text.y=element_text(size=16),     
          strip.text.x=element_text(size=16),    
          axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.title=element_text(size=16),
          legend.position="bottom")
  save_plot(paste("sem/pearson_raw_muts_", scal, ".pdf", sep=""), p, base_height=7, base_width=16)
}

#################
#
# Fit measures & model selection
#
#################

human_maps_10kb <- fread("maps/maps_10kb.csv.gz") 
human_maps_100kb <- fread("maps/maps_100kb.csv.gz") 
human_maps_1Mb <- fread("maps/maps_1Mb.csv.gz") 

## 10 kb
gw_fitmeasures_10kb_samechrom <- data.frame()
gw_fitmeasures_10kb_freechrom <- data.frame()
for(dag in 2:4) {
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_10kb_genomewide", 
                       "_latents_", m, "_freechrom.csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "freechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_10kb_freechrom <- rbind.data.frame(gw_fitmeasures_10kb_freechrom, tmp)
    
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_10kb_genomewide", 
                       "_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "samechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_10kb_samechrom <- rbind.data.frame(gw_fitmeasures_10kb_samechrom, tmp)
  }
}
gw_fitmeasures_10kb_samechrom$scale <- 1e+4
gw_fitmeasures_10kb_freechrom$scale <- 1e+4

## 100 kb
gw_fitmeasures_100kb_samechrom <- data.frame()
gw_fitmeasures_100kb_freechrom <- data.frame()
for(dag in 2:4) {
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_100kb_genomewide", 
                       "_latents_", m, "_freechrom.csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "freechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_100kb_freechrom <- rbind.data.frame(gw_fitmeasures_100kb_freechrom, tmp)
    
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_100kb_genomewide", 
                       "_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "samechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_100kb_samechrom <- rbind.data.frame(gw_fitmeasures_100kb_samechrom, tmp)
  }
}
gw_fitmeasures_100kb_samechrom$scale <- 1e+5
gw_fitmeasures_100kb_freechrom$scale <- 1e+5

## 1 Mb
gw_fitmeasures_1Mb_samechrom <- data.frame()
gw_fitmeasures_1Mb_freechrom <- data.frame()
for(dag in 2:4) {
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_1Mb_genomewide", 
                       "_latents_", m, "_freechrom.csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "freechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_1Mb_freechrom <- rbind.data.frame(gw_fitmeasures_1Mb_freechrom, tmp)
    
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG",
                       dag, "_fitmeasures_1Mb_genomewide", 
                       "_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    tmp$method <- "samechrom"
    
    tmp <- dplyr::select(tmp, c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model))
    gw_fitmeasures_1Mb_samechrom <- rbind.data.frame(gw_fitmeasures_1Mb_samechrom, tmp)
  }
}
gw_fitmeasures_1Mb_samechrom$scale <- 1e+6
gw_fitmeasures_1Mb_freechrom$scale <- 1e+6

gw_fitmeasures_samechrom <- rbind.data.frame(gw_fitmeasures_10kb_samechrom,
                                             gw_fitmeasures_100kb_samechrom,
                                             gw_fitmeasures_1Mb_samechrom) %>%
  dplyr::select(c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model, scale))

gw_fitmeasures_freechrom <- rbind.data.frame(gw_fitmeasures_10kb_freechrom,
                                             gw_fitmeasures_100kb_freechrom,
                                             gw_fitmeasures_1Mb_freechrom) %>%
  dplyr::select(c(pvalue, cfi, gfi, rmsea, method, DAG, constrained_model, scale))

gw_fitmeasures_latent <- rbind.data.frame(gw_fitmeasures_freechrom, gw_fitmeasures_samechrom)

# DAG 2 is just-identified 
p <- ggplot(data=filter(gw_fitmeasures_latent, DAG!=2), 
            aes(x=scale/1e3, y=-log10(pvalue), color=as.factor(DAG))) +
  geom_point(size=3, shape=2) + geom_hline(yintercept=-log10(0.05), linetype="dashed", color="darkgrey") +
  facet_wrap(~constrained_model, labeller=labeller(constrained_model=model_labels)) + # NOTE check labeller
  scale_x_log10(breaks=c(10, 100, 1000)) +
  scale_color_manual(values=c("purple3", "brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Scale (kb)", y=expression(-log[10](italic(p)))) + theme_classic() +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),      
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_pvals_latent_freechrom_vs_same.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=filter(gw_fitmeasures_latent, DAG!=2),  
            aes(x=scale, y=cfi, color=method)) +
  geom_point(size=3) +
  geom_hline(yintercept=0.9, linetype="dashed", color="darkgrey") +
  facet_grid(DAG~constrained_model, labeller=labeller(constrained_model=model_labels)) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_log10(breaks=c(1e+4, 1e+5, 1e+6)) +
  scale_color_manual(values=c("cyan3", "brown1")) +
  labs(title="CFI for genome-wide models, latent variables", x="Scale", y="CFI") +
  theme(strip.text.y=element_text(size=16),  
        strip.text.x=element_text(size=16),  
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_cfi_latent_freechrom_vs_same.pdf", q, base_height=10, base_width=20)

# per chromosome SEM models
## 10 kb
chr_fitmeasures_10kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag,
                         "_fitmeasures_10kb_chr", 
                         c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_fitmeasures_10kb <- rbind.data.frame(chr_fitmeasures_10kb, df)
  }
}
chr_fitmeasures_10kb$scale <- 1e+4

## 100 kb
chr_fitmeasures_100kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_fitmeasures_100kb_chr", 
                         c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_fitmeasures_100kb <- rbind.data.frame(chr_fitmeasures_100kb, df)
  }
}
chr_fitmeasures_100kb$scale <- 1e+5

## 1 Mb
chr_fitmeasures_1Mb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_fitmeasures_1Mb_chr", 
                         c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_fitmeasures_1Mb <- rbind.data.frame(chr_fitmeasures_1Mb, df)
  }
}
chr_fitmeasures_1Mb$scale <- 1e+6

chr_fit_10kb <- dplyr::select(chr_fitmeasures_10kb, c("pvalue", "aic", "bic", "cfi", "gfi", "chrom", "DAG", "constrained_model", "scale"))
chr_fit_100kb <- dplyr::select(chr_fitmeasures_100kb, c("pvalue", "aic", "bic", "cfi", "gfi", "chrom", "DAG", "constrained_model", "scale"))
chr_fit_1Mb <- dplyr::select(chr_fitmeasures_1Mb, c("pvalue", "aic", "bic", "cfi", "gfi", "chrom", "DAG", "constrained_model", "scale"))

chr_fitmeasures_latent <- rbind.data.frame(chr_fit_10kb, chr_fit_100kb, chr_fit_1Mb) 
chr_fitmeasures_latent$constrained_model <- factor(chr_fitmeasures_latent$constrained_model, 
                                                   levels = names(elem_labels), 
                                                   labels = unname(elem_labels)) 

p <- ggplot(data=chr_fitmeasures_latent, aes(x=chrom, y=-log10(pvalue), color=as.factor(DAG))) +
  geom_point(size=3) + 
  geom_hline(yintercept=-log10(0.05/num_chrom), linetype="dashed", color="darkgrey") +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y=expression(-log[10](italic(p)))) +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_pvals_latent.pdf", p, base_height=8, base_width=15)

chr_fitmeasures_latent <- chr_fitmeasures_latent %>% 
  mutate(scale_offset = case_when(DAG == 3 ~ scale * 0.8, 
                                  DAG == 4 ~ scale * 1.2,
                                  TRUE ~ scale))

fwrite(dplyr::select(chr_fitmeasures_latent, c(pvalue, cfi, chrom, DAG, constrained_model, scale)),
       "sem/obspi_chr_fitmeasures.csv")

q <- ggplot(data=chr_fitmeasures_latent, aes(x=chrom, y=cfi, color=as.factor(DAG))) +
  geom_point(size=3) + 
  geom_hline(yintercept=0.9, linetype="dashed", color="darkgrey") +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="CFI") +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_cfi_latent.pdf", q, base_height=8, base_width=15)

p2 <- ggplot(data=chr_fitmeasures_latent, aes(x=scale_offset / 1e3, y=-log10(pvalue), color=as.factor(DAG))) +
  geom_point(size=3, shape=2) +
  #geom_text(aes(label=chrom), vjust=2, size=4, 
  #          position=position_jitter(width=0.15, height=0.05)) +
  geom_hline(yintercept=-log10(0.05/num_chrom), linetype="dashed", color="darkgrey") +
  facet_wrap(~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_log10(breaks=c(10, 100, 1000)) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x=NULL, y=expression(-log[10](italic(p)))) +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text.y=element_text(size=16), 
        axis.text.x=element_blank(),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="none")

# fake plot for legend
fake <- ggplot(chr_fitmeasures_latent, aes(x=1, y=1, color=as.factor(DAG))) +
  geom_point(size = 4) +   
  scale_color_manual(values = c("brown1", "cyan3"), name = "DAG") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 16),   
        legend.title = element_text(size = 16))
legend <- cowplot::get_legend(fake)

q2 <- ggplot(data=chr_fitmeasures_latent, aes(x=scale_offset / 1e3, y=cfi, color=as.factor(DAG))) +
  #geom_text(aes(label=chrom), vjust=2, size=4,
  #          position=position_jitter(width=0.15, height=0.05)) +
  geom_point(size=3, shape=2) +
  geom_hline(yintercept=0.9, linetype="dashed", color="darkgrey") +
  facet_wrap(~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_log10(breaks=c(10, 100, 1000)) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Scale (kb)", y="CFI") +
  theme(strip.text.x=element_blank(),       
        axis.title=element_text(size=18), 
        axis.text=element_text(size=16), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="none")
x <- plot_grid(plot_grid(p2, q2, ncol=1, align="v", labels="AUTO", rel_heights=c(1, 1.175)), legend, nrow=2, rel_heights=c(1, 0.05))
save_plot("sem/chr_fit_compressed.pdf", x, base_height=7.5, base_width=15)

# (Nested) model selection, genome-wide models, free or equal-chr regressions (LRT)
## 10kb
LRT_gw_freechrom_10kb <- data.frame()
for(m in constrained_models) { 
  for(d in 1:4) {
    
    path <- paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_10kb_latents_", m, ".csv")
    
    tmp <- if(file.exists(path)) {
      fread(path)
    } else {
      NULL
    } 
    
    df <- as.data.frame(tmp$`Pr(>Chisq)`[2],)  
    df$constrained_model <- m
    df$dag <- d
    
    LRT_gw_freechrom_10kb <- rbind.data.frame(LRT_gw_freechrom_10kb, df)
  }
}
LRT_gw_freechrom_10kb$scale <- 1e+4

## 100 kb
LRT_gw_freechrom_100kb <- data.frame()
for(m in constrained_models) { 
  for(d in 1:4) { 
    
    path <- paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_100kb_latents_", m, ".csv")
    
    tmp <- if(file.exists(path)) {
      fread(path)
    } else {
      NULL
    } 
    
    df <- as.data.frame(tmp$`Pr(>Chisq)`[2],)  
    df$constrained_model <- m
    df$dag <- d
    
    LRT_gw_freechrom_100kb <- rbind.data.frame(LRT_gw_freechrom_100kb, df)
  }
}
LRT_gw_freechrom_100kb$scale <- 1e+5

## 1 Mb
LRT_gw_freechrom_1Mb <- data.frame()
for(m in constrained_models) { 
  for(d in 2:4) { 
    
    path <- paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_1Mb_latents_", m, ".csv")
    
    tmp <- if(file.exists(path)) {
      fread(path)
    } else {
      NULL
    } 
    
    df <- as.data.frame(tmp$`Pr(>Chisq)`[2],)  
    df$constrained_model <- m
    df$dag <- d
    
    LRT_gw_freechrom_1Mb <- rbind.data.frame(LRT_gw_freechrom_1Mb, df)
  }
}
LRT_gw_freechrom_1Mb$scale <- 1e+6

gw_LRT <- rbind.data.frame(LRT_gw_freechrom_10kb, LRT_gw_freechrom_100kb, LRT_gw_freechrom_1Mb)
names(gw_LRT)[1] <- "pvalue"
fwrite(gw_LRT, "sem/obspi_gw_LTR_freechrom.csv")

p <- ggplot(data=gw_LRT, aes(x=scale/1e3,  y=-log10(pvalue), shape=as.factor(dag), color=constrained_model)) +
  geom_point(size=3) + theme_classic() + 
  geom_hline(yintercept=-log10(0.05), linetype="dashed", color="darkgrey") +
  scale_x_log10(breaks=c(10, 100, 1000)) +
  scale_shape_manual(values=c(0, 1, 2, 3), name="DAG") +
  scale_color_manual(values=c("purple3", "seagreen4", "brown1", "cyan3"),
                     labels = c("split_cds_regulatory"="CDS + Regulatory", "split_cds_phastcons"="CDS + phastCons"),
                     name=NULL) +
  labs(title=NULL, x="Scale (kb)", y=expression(-log[10](italic(p)))) +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),      
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_LRT_latent_freechrom.pdf", p, base_height=6, base_width=8)

p2 <- ggplot(data=filter(gw_LRT, dag==3 | dag==4, scale==1e6), 
             aes(x=constrained_model, y=-log10(pvalue), color=as.factor(dag))) +
  geom_point(size=3) + theme_classic() + 
  geom_hline(yintercept=-log10(0.05), linetype="dashed", color="darkgrey") +
  scale_x_discrete(labels = c("split_cds_regulatory" = "CDS + Regulatory", "split_cds_phastcons" = "CDS + phastCons")) +
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Elements", y=expression(-log[10](italic(p)))) +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=14), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_LRT_latent_freechrom.pdf", p2, base_height=5, base_width=9)

# (Nested) model selection, DAGs 3 and 4 (LRT)
# (DAG 4 adds a covariance term between constrained sites and mutation rates)
# per chr models
## 10 kb
chr_LRT_10kb <- data.frame()
for(m in constrained_models) { 
  chr_list <- list(length=num_chrom)
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/lavaan_out/obspi_LRT_DAG3_DAG4_10kb_chr",
                       c, "_latents_", m, ".csv", sep=""))
    
    tmp <- as.data.frame(tmp$`Pr(>Chisq)`[2],)  
    tmp$chrom <- c
    tmp$constrained_model <- m
    
    chr_list[[c]] <- tmp
  }
  
  df <- do.call(rbind.data.frame, chr_list)
  chr_LRT_10kb <- rbind.data.frame(chr_LRT_10kb, df)
}
chr_LRT_10kb$scale <- 1e+4

## 100 kb
chr_LRT_100kb <- data.frame()
for(m in constrained_models) { 
  chr_list <- list(length=num_chrom)
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/lavaan_out/obspi_LRT_DAG3_DAG4_100kb_chr",
                       c, "_latents_", m, ".csv", sep=""))
    
    tmp <- as.data.frame(tmp$`Pr(>Chisq)`[2],)  
    tmp$chrom <- c
    tmp$constrained_model <- m
    
    chr_list[[c]] <- tmp
  }
  
  df <- do.call(rbind.data.frame, chr_list)
  chr_LRT_100kb <- rbind.data.frame(chr_LRT_100kb, df)
}
chr_LRT_100kb$scale <- 1e+5

## 1 Mb
chr_LRT_1Mb <- data.frame()
for(m in constrained_models) { 
  chr_list <- list(length=num_chrom)
  for(c in 1:num_chrom) {
    
    tmp <- fread(paste("sem/lavaan_out/obspi_LRT_DAG3_DAG4_1Mb_chr",
                       c, "_latents_", m, ".csv", sep=""))
    
    tmp <- as.data.frame(tmp$`Pr(>Chisq)`[2],)
    tmp$chrom <- c
    tmp$constrained_model <- m
    
    chr_list[[c]] <- tmp
  }
  
  df <- do.call(rbind.data.frame, chr_list)
  chr_LRT_1Mb <- rbind.data.frame(chr_LRT_1Mb, df)
}
chr_LRT_1Mb$scale <- 1e+6

chr_LRT_latent <- rbind.data.frame(chr_LRT_10kb, chr_LRT_100kb, chr_LRT_1Mb)
names(chr_LRT_latent)[1] <- "pvalue"

pc <- ggplot(data=chr_LRT_latent, aes(x=chrom, y=-log10(pvalue))) +
  geom_point(size=3) + theme_classic() + 
  geom_hline(yintercept=-log10(0.05/num_chrom), linetype="dashed", color="darkgrey") +
  facet_grid(scale/1e3~constrained_model, scale="free_y", labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) +
  labs(title=NULL, x=NULL, y=expression(-log[10](italic(p)))) +
  theme(strip.text=element_text(size=16),      
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12))
save_plot("sem/chr_LRT_DAGs3vs4.pdf", pc, base_height=8, base_width=14)

#################
#
# Variance explained 
#
#################

# genome-wide models, DAGs 1-2 
## 10 kb
gw_r2_10kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_10kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_10kb <- rbind.data.frame(gw_r2_10kb, tmp)
  }
}
gw_r2_10kb$scale <- 1e+4

## 100 kb
gw_r2_100kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_100kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_100kb <- rbind.data.frame(gw_r2_100kb, tmp)
  }
}
gw_r2_100kb$scale <- 1e+5

## 1 Mb
gw_r2_1Mb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_1Mb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_1Mb <- rbind.data.frame(gw_r2_1Mb, tmp)
  }
}
gw_r2_1Mb$scale <- 1e+6

gw_r2 <- rbind.data.frame(gw_r2_10kb, gw_r2_100kb, gw_r2_1Mb) 

gw_r2_B <- pivot_longer(gw_r2, cols=ends_with(".B"))
gw_r2_pi <- pivot_longer(gw_r2, cols=ends_with(".avg_pi"))

p <- ggplot(data=gw_r2_pi, aes(x=name, y=value * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels), scales="free_y") + 
  scale_y_continuous(breaks=pretty_breaks()) + 
  scale_x_discrete(labels=as.character(1:num_chrom)) +
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),        
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_r2_pi_DAGs1-2_latents.pdf", p, base_height=10, base_width=20)

q <- ggplot(data=gw_r2_B, aes(x=name, y=value, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale~constrained_model, labeller=labeller(constrained_model=model_labels), scales="free_y") + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 1)) + 
  scale_x_discrete(labels=as.character(1:num_chrom)) +
  scale_color_manual(values=c("cyan3", "brown1"),  name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),        
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_r2_B_DAGs1-2_latents.pdf", q, base_height=10, base_width=20)

# per chromosome SEM models, DAGs 1-2
## 10 kb
chr_r2_10kb <- data.frame()
for(dag in 1:2) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_10kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_10kb <- rbind.data.frame(chr_r2_10kb, df)
  }
}
chr_r2_10kb$scale <- 1e+4

## 100 kb
chr_r2_100kb <- data.frame()
for(dag in 1:2) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_100kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_100kb <- rbind.data.frame(chr_r2_100kb, df)
  }
}
chr_r2_100kb$scale <- 1e+5

## 1 Mb
chr_r2_1Mb <- data.frame()
for(dag in 1:2) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_1Mb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_1Mb <- rbind.data.frame(chr_r2_1Mb, df)
  }
}
chr_r2_1Mb$scale <- 1e+6

# NOTE: there are no fit measures available for DAGs 1-2
chr_r2_DAGs12 <- rbind.data.frame(chr_r2_10kb, chr_r2_100kb, chr_r2_1Mb)

p <- ggplot(data=chr_r2_DAGs12, aes(x=chrom, y=avg_pi * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),    
        strip.text.x=element_text(size=16),    
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_pi_DAGs1-2_latents.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=chr_r2_DAGs12, aes(x=chrom, y=B * 100, color=as.factor(DAG))) +
  geom_point(size=3) + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),        
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_B_DAGs1-2_latents.pdf", q, base_height=6, base_width=12)

# genome-wide models, DAGs 3-4
## 10 kb
gw_r2_10kb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_10kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_10kb <- rbind.data.frame(gw_r2_10kb, tmp)
  }
}
gw_r2_10kb$scale <- 1e+4

## 100 kb
gw_r2_100kb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_100kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_100kb <- rbind.data.frame(gw_r2_100kb, tmp)
  }
}
gw_r2_100kb$scale <- 1e+5

## 1 Mb
gw_r2_1Mb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_r2_1Mb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_r2_1Mb <- rbind.data.frame(gw_r2_1Mb, tmp)
  }
}
gw_r2_1Mb$scale <- 1e+6

gw_r2_latent <- rbind.data.frame(gw_r2_10kb, gw_r2_100kb, gw_r2_1Mb) 

gw_r2_B <- pivot_longer(gw_r2_latent, cols=ends_with(".B"))
gw_r2_pi <- pivot_longer(gw_r2_latent, cols=ends_with(".avg_pi"))
gw_r2_mut <- pivot_longer(gw_r2_latent, cols=ends_with(".avg_mut"))

p <- ggplot(data=gw_r2_pi, aes(x=name, y=value * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_discrete(labels=as.character(1:num_chrom)) +
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),          
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_r2_pi_DAGs3-4.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=gw_r2_B, aes(x=name, y=value * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_discrete(labels=as.character(1:num_chrom)) +
  scale_shape_manual(values=c(0, 1)) +
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),    
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_r2_B_DAGs2-3.pdf", q, base_height=6, base_width=12)

# per chromosome SEM models, DAGs 3-4
## 10 kb
chr_r2_10kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_10kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_10kb <- rbind.data.frame(chr_r2_10kb, df)
  }
}
chr_r2_10kb$scale <- 1e+4

## 100 kb
chr_r2_100kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_100kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_100kb <- rbind.data.frame(chr_r2_100kb, df)
  }
}
chr_r2_100kb$scale <- 1e+5

## 1 Mb
chr_r2_1Mb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_r2_1Mb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_r2_1Mb <- rbind.data.frame(chr_r2_1Mb, df)
  }
}
chr_r2_1Mb$scale <- 1e+6

chr_r2_DAGs34 <- rbind.data.frame(chr_r2_10kb, chr_r2_100kb, chr_r2_1Mb)

chr_r2_ext_DAGs34 <- left_join(chr_r2_DAGs34, 
                               chr_fitmeasures_latent,
                               by=c("chrom", "DAG", "constrained_model",  "scale"))

p <- ggplot(data=chr_r2_ext_DAGs34, aes(x=chrom, y=avg_pi * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("cyan3", "brown1"), name="DAG") +
  labs(title=NULL,  x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),    
        strip.text.x=element_text(size=16),         
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_pi_DAGs3-4_latents.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=chr_r2_ext_DAGs34, aes(x=chrom, y=B * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_B_DAGs3-4_latents.pdf", q, base_height=6, base_width=12)

q <- ggplot(data=chr_r2_ext_DAGs34, aes(x=chrom, y=avg_mut * 100, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Variance Explained (%)") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_mut_DAGs3-4_latents.pdf", q, base_height=6, base_width=12)

chr_r2_dags <- rbind.data.frame(chr_r2_DAGs12, dplyr::select(chr_r2_DAGs34, -avg_mut))

chr_r2_dags$constrained_model <- factor(chr_r2_dags$constrained_model, 
                                        levels = names(elem_labels), 
                                        labels = unname(elem_labels)) 

# summaries
#chr_r2_dags[, `:=`(min_r2=min(avg_pi), max_r2=max(avg_pi)), by=.(DAG, constrained_model, scale)]
#chr_r2_dags_unique <- chr_r2_dags[, .SD[1], by = .(DAG, constrained_model, scale)]
chr_r2_dags[, `:=`(min_r2=min(avg_pi), max_r2=max(avg_pi)), by=scale]
chr_r2_dags[!duplicated(scale)]
chr_r2_dags[chrom==22,]
# end summaries

mean_dat <- chr_r2_dags %>% group_by(DAG, constrained_model, scale) %>%
  summarise(mean_r2_pi=mean(avg_pi),
            mean_r2_B=mean(B)) %>% ungroup()

r <- ggplot(data=chr_r2_dags, aes(x=chrom, y=avg_pi, color=as.factor(DAG))) +
  geom_point(size=3, shape=2) + 
  geom_hline(data=mean_dat, 
             aes(yintercept=mean_r2_pi, col=as.factor(DAG)),
             linetype="dashed") +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0,1)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("purple3", "seagreen4", "brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y=expression(R[pi]^2)) +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_pi_latents.pdf", r, base_height=8, base_width=15)

chr_r2_dags %>% filter(., scale==1e4) %>% summarise(., max_10kb = max(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., scale==1e4) %>% summarise(., min_10kb = min(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., scale==1e5) %>% summarise(., max_100kb = max(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., scale==1e5) %>% summarise(., max_100kb = min(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., scale==1e6) %>% summarise(., max_1Mb = max(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., scale==1e6) %>% summarise(., min_1Mb = min(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., DAG==4, scale==1e6, constrained_model=="CDS + phastCons") %>% summarise(., min_1Mb = min(avg_pi, na.rm = TRUE))
chr_r2_dags %>% filter(., DAG==4, chrom==19, scale==1e6, constrained_model=="CDS + phastCons")
chr_r2_dags %>% filter(., DAG==3, chrom==19, scale==1e6, constrained_model=="CDS + phastCons")

chr_r2_dags <- chr_r2_dags %>%
  mutate(scale_offset = case_when(DAG == 1 ~ scale * 0.75,
                                  DAG == 2 ~ scale * 0.88,
                                  DAG == 3 ~ scale * 1.15, 
                                  DAG == 4 ~ scale * 1.325,
                                  TRUE ~ scale))
fwrite(dplyr::select(chr_r2_dags, c(avg_pi, chrom, DAG, constrained_model, scale)), "sem/obspi_chr_r2pi.csv")

# fake plot to extract legend
fake <- ggplot(chr_r2_dags, aes(x = 1, y = 1, color = as.factor(DAG))) +
  geom_point(size = 4) +   
  scale_color_manual(values=c("purple3", "seagreen4", "brown1", "cyan3"), name="DAG") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 16),   
        legend.title = element_text(size = 16))
chr_r2_dags_legend <- cowplot::get_legend(fake)

chr_r2_dags_p <- ggplot(data=chr_r2_dags, aes(x=scale_offset/1e3,  y=avg_pi*100, color=as.factor(DAG))) +
  #geom_text(aes(label=chrom), vjust=2, size=4,
  #          position=position_jitter(width=0.15, height=0.025)) +
  geom_point(size=3, shape=2) + 
  facet_wrap(~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0,100)) +
  scale_x_log10(breaks=c(10, 100, 1000)) + 
  scale_color_manual(values=c("purple3", "seagreen4", "brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x=NULL, y=expression(R[pi]^2)) +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.ticks.x=element_blank(),
        axis.text=element_text(size=16), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_pi_latents_compressed.pdf", chr_r2_dags_p, base_height=5, base_width=15)

# slides
s2 <- ggplot(data=filter(chr_r2_dags, constrained_model=="phastCons", scale==1e6, DAG==3 | DAG==4), 
             aes(x=chrom, y=avg_pi*100, color=as.factor(DAG))) +
  geom_point(size=3, shape=2) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0,100)) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y=expression(R[pi]^2)) +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_r2_pi_simplified.pdf", s2, base_height=5, base_width=10)

#################
#
# Parameter estimates 
#
#################

# genome-wide, DAGs 1-2
## 10 kb
gw_params_10kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_10kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_10kb <- rbind.data.frame(gw_params_10kb, tmp)
  }
}
gw_params_10kb$scale <- 1e+4

## 100 kb
gw_params_100kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_100kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_100kb <- rbind.data.frame(gw_params_100kb, tmp)
  }
}
gw_params_100kb$scale <- 1e+5

## 1 Mb
gw_params_1Mb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_1Mb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_1Mb <- rbind.data.frame(gw_params_1Mb, tmp)
  }
}
gw_params_1Mb$scale <- 1e+6

gw_params <- rbind.data.frame(gw_params_10kb, gw_params_100kb, gw_params_1Mb) %>%
  filter(., block==1,  op=="~") # all blocks (chr) share PC's in genomewide model

gw_params$sig <- gw_params$pvalue < 0.05 / num_chrom # Bonferroni over autosomes
  
p <- ggplot(data=filter(gw_params, lhs=="avg_pi"), 
            aes(x=rhs, y=est, shape=sig, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_discrete() +
  scale_shape_manual(values=c(16, 17), name="Significant?") +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Variable", y="Direct Std. PC to Diversity") +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),         
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_PCs_pi_DAGs1-2.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=filter(gw_params, lhs=="B"), 
            aes(x=rhs, y=est, shape=sig, color=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") + 
  facet_grid(scale~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks()) + 
  scale_shape_manual(values=c(16, 17), name="Significant?") +
  scale_x_discrete() + theme_classic() + 
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Variable", y="Direct Std. PC to B") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_PCs_B_DAGs1-2.pdf", q, base_height=6, base_width=12)

# per chromosome SEM models, DAGs 1-2
## 10 kb
chr_params_10kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_10kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_10kb <- rbind.data.frame(chr_params_10kb, df)
  }
}
chr_params_10kb$scale <- 1e+4

## 100 kb
chr_params_100kb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_100kb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_100kb <- rbind.data.frame(chr_params_100kb, df)
  }
}
chr_params_100kb$scale <- 1e+5

## 1 Mb
chr_params_1Mb <- data.frame()
for(dag in 1:2) { 
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_1Mb_chr", c, "_latents_", m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_1Mb <- rbind.data.frame(chr_params_1Mb, df)
  }
}
chr_params_1Mb$scale <- 1e+6

chr_params <- rbind.data.frame(chr_params_10kb, chr_params_100kb, chr_params_1Mb) %>%
  filter(., op=="~" | op==":=") 

chr_params$sig <- chr_params$pvalue < 0.05 / num_chrom # Bonferroni over autosomes

p <- ggplot(data=filter(chr_params, lhs=="avg_pi"), 
            aes(x=chrom, y=est, color=as.factor(DAG), shape=rhs)) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks()) + theme_classic() + 
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_shape_manual(values=c(0, 1, 2), labels=c("avg_mut"=expression(mu),
                                                 "B"="B",
                                                 "prop_del_sites"="E"),
                     name=NULL) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Direct PC to Diversity") +
  theme(strip.text.y=element_text(size=16),  
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_params_pi_latents_DAGs1-2.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=filter(chr_params, lhs=="B"), 
            aes(x=chrom, y=est, color=as.factor(DAG), shape=rhs)) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_shape_manual(values=c(0, 1, 2), labels=c("avg_mut"=expression(mu),
                                                 "prop_del_sites"="E"),
                     name=NULL) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Chromosome", y="Direct PC to B") +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_params_B_latents_DAGs1-2.pdf", q, base_height=6, base_width=12)

# genome-wide, DAGs 3-4
## 10 kb
gw_params_10kb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_10kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_10kb <- rbind.data.frame(gw_params_10kb, tmp)
  }
}
gw_params_10kb$scale <- 1e+4

## 100 kb
gw_params_100kb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_100kb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_100kb <- rbind.data.frame(gw_params_100kb, tmp)
  }
}
gw_params_100kb$scale <- 1e+5

## 1 Mb
gw_params_1Mb <- data.frame()
for(dag in 3:4) { 
  for(m in constrained_models) { 
    tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                       "_params_1Mb_genomewide_latents_", m, ".csv", sep=""))
    
    tmp$DAG <- dag
    tmp$constrained_model <- m
    
    gw_params_1Mb <- rbind.data.frame(gw_params_1Mb, tmp)
  }
}
gw_params_1Mb$scale <- 1e+6

gw_params <- rbind.data.frame(gw_params_10kb, gw_params_100kb, gw_params_1Mb) %>%
  filter(., block==1, op=="~") # all blocks (chr) share PC's in G-W model
          
gw_params$sig <- gw_params$pvalue < 0.05 / num_chrom # Bonferroni over autosomes

p <- ggplot(data=filter(gw_params, lhs=="avg_pi"), 
            aes(x=rhs, y=est, shape=sig, color=as.factor(DAG))) +
  geom_point(size=3) + theme_classic() + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(0, 1)) + 
  scale_shape_manual(values=c(16, 17), name="Significant?") +
  scale_x_discrete() +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Variable", y="Direct PC to Diversity") +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),      
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_PCs_pi_DAGs3-4_latents.pdf", p, base_height=6, base_width=12)

q <- ggplot(data=filter(gw_params, lhs=="B"), 
            aes(x=rhs, y=est, shape=sig, color=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") + 
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks(), limits=c(-1, 1)) + 
  scale_shape_manual(values=c(16, 17), name="Significant?") +
  scale_x_discrete() + theme_classic() + 
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Variable", y="Direct PC to B") +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),   
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/gw_PCs_B_DAGs3-4_latents.pdf", q, base_height=6, base_width=12)

# per chromosome SEM models DAGs 3-4
## 10 kb
chr_params_10kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_10kb_chr", c, "_latents_", 
                         m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_10kb <- rbind.data.frame(chr_params_10kb, df)
  }
}
chr_params_10kb$scale <- 1e+4

## 100 kb
chr_params_100kb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_100kb_chr", c, "_latents_", 
                         m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_100kb <- rbind.data.frame(chr_params_100kb, df)
  }
}
chr_params_100kb$scale <- 1e+5

## 1 Mb
chr_params_1Mb <- data.frame()
for(dag in 3:4) {
  for(m in constrained_models) { 
    chr_list <- list(length=num_chrom)
    for(c in 1:num_chrom) {
      tmp <- fread(paste("sem/lavaan_out/obspi_YRI_DAG", dag, 
                         "_params_1Mb_chr", c, "_latents_", 
                         m, ".csv", sep=""))
      
      tmp$chrom <- c
      tmp$DAG <- dag
      tmp$constrained_model <- m
      
      chr_list[[c]] <- tmp
    }
    
    df <- do.call(rbind.data.frame, chr_list)
    chr_params_1Mb <- rbind.data.frame(chr_params_1Mb, df)
  }
}
chr_params_1Mb$scale <- 1e+6

chr_params <- rbind.data.frame(chr_params_10kb, chr_params_100kb, chr_params_1Mb)  %>%
  filter(., op=="~" | op==":=" | (lhs=="avg_mut" & op=="~~" & rhs=="prop_del_sites"))

chr_params$constrained_model <- factor(chr_params$constrained_model, 
                                       levels = names(elem_labels), 
                                       labels = unname(elem_labels)) 

# summaries
pcs <- filter(chr_params, DAG==4, lhs=="avg_pi", rhs=="avg_mut" | rhs=="B", pvalue < 0.05/22) %>% setDT()
pcs_wd <- dcast(pcs, chrom + DAG + constrained_model + scale ~ rhs, value.var = "est") %>% filter(., avg_mut > 0) %>% setDT()
pcs_wd[, ratio:=B/avg_mut]
pcs_wd[, `:=`(min_ratio=min(ratio, na.rm=T), max_ratio=max(ratio, na.rm=T), mean_ratio=mean(ratio, na.rm=T)), 
       by=.(constrained_model, scale)]
pcs_wd_unique <- pcs_wd[, .SD[1], by = .(constrained_model, scale)]
pcs_wd_unique
# end summaries

chr_params$sig <- chr_params$pvalue < 0.05 / num_chrom # Bonferroni over autosomes
chr_params_ext <- left_join(chr_params, chr_fitmeasures_latent,
                            by=c("chrom", "DAG", "constrained_model","scale"))

names(chr_params_ext)[8] <- "pvalue_est"
names(chr_params_ext)[16] <- "pvalue_DAG"

p1 <- ggplot(data=filter(chr_params_ext, lhs=="avg_pi"), 
             aes(x=chrom, y=est, alpha=sig, color=rhs, shape=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) +
  scale_y_continuous(breaks=pretty_breaks()) + theme_classic() + 
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_shape_manual(values=c(1, 2), name="DAG") +
  scale_color_manual(values = c("purple3", "seagreen4", "brown1"),
                     labels = c( "avg_mut" = expression(mu %->% pi), 
                                 "B" = expression(B %->% pi), 
                                 "prop_del_sites" = expression(E %->% pi)),
                     name = NULL) +
  labs(title=NULL, x="Chromosome", y=expression(Path~Coefficient~to~pi)) +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_params_pi_latents.pdf", p1, base_height=7, base_width=16)

q1 <- ggplot(data=filter(chr_params_ext, lhs=="B"), 
             aes(x=chrom, y=est, alpha=sig, color=rhs, shape=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) +
  scale_y_continuous(breaks=pretty_breaks()) +  theme_classic() + 
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_shape_manual(values=c(1, 2), name="DAG") +
  scale_color_manual(values = c("purple3", "seagreen4", "brown1"),
                     labels = c( "avg_mut" = expression(mu %->% B), 
                                 "avg_rec" = expression(r %->% B), 
                                 "prop_del_sites" = expression(E %->% B)),
                     name = NULL ) +
  labs(title=NULL, x="Chromosome", y=expression(Path~Coefficient~to~B)) +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_params_B_latents.pdf", q1, base_height=7, base_width=16)

r1 <- ggplot(data=filter(chr_params_ext, label=="rec_B_pi" | label=="rec_mu_pi"), 
             aes(x=chrom, y=est, alpha=sig, color=label, shape=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels), scale="free_y") + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) + theme_classic() + 
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_shape_manual(values=c(1, 2), name="DAG") +
  scale_color_manual(values = c("seagreen4", "brown1"),
                     labels = list(bquote(r %->% B %->% pi),
                                   bquote(r %->% mu %->% pi)), name=NULL) +
  labs(title=NULL, x="Chromosome", y=expression(Path~Coefficient~to~pi)) +
  theme(strip.text.y=element_text(size=16),        
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_params_r_latents.pdf", r1, base_height=7, base_width=16)

chr_params_ext[op=="~~",]$rhs <- "covar"
chr_params_ext$is_19 <- chr_params_ext$chrom==19

fwrite(dplyr::select(chr_params_ext, -c(aic, bic, cfi, gfi, scale_offset)), "sem/obspi_chr_PC_DAGs.csv")

pp2 <- ggplot(data=filter(chr_params_ext, rhs=="avg_rec"), 
              aes(x=chrom, y=est, alpha=sig, color=lhs, shape=as.factor(DAG))) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels), scale="free_y") + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=1:num_chrom) + theme_classic() + 
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_shape_manual(values=c(1, 2), name="DAG") +
  scale_color_manual(values = c("purple3", "seagreen4"),
                     labels = c("avg_mut" = expression(r %->% mu), 
                                "B" = expression(r %->% B)),
                     name = NULL ) +
  labs(title=NULL, x="Chromosome", y=expression(Path~Coefficient~from~r)) +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),     
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_pcs_rec_latents.pdf", pp2, base_height=7, base_width=16)

p3 <- ggplot(data=filter(chr_params_ext, DAG==4, lhs=="avg_pi" | lhs=="rec_B_pi" | lhs=="rec_mu_pi" | op=="~~"),
             aes(x=rhs, y=est, alpha=sig, color=is_19)) +
  geom_point(size=2) + 
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_color_manual(values=c("cyan3", "brown1"), labels=c("TRUE"="Chr 19", "FALSE"="Others"), name=NULL) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_discrete(labels = c("avg_mut" = expression(mu %->% pi),
                              "c1*c7" = expression(r %->% mu %->% pi),
                              "c2*c6" = expression(r %->% B %->% pi),
                              "B" = expression(B %->% pi),
                              "prop_del_sites" = expression(E %->% pi),
                              "covar" = expression(mu %~% E))) +
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  labs(title=NULL, x="Path", y="Coefficient") +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=14), 
        axis.text.x = element_text(margin=margin(t=10)),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
        axis.line = element_blank(),
        legend.position="bottom")
save_plot("sem/chr_PC_DAG4.pdf", p3, base_height=7, base_width=14)

# slides
p4 <- ggplot(data=filter(chr_params_ext,
                         constrained_model=="split_cds_phastcons", scale==1e6,
                         rhs!="prop_del_sites",
                         DAG==4, lhs=="avg_pi" | lhs=="rec_B_pi" | lhs=="rec_mu_pi"),
             aes(x=rhs, y=est, color=is_19, shape=is_19)) +
  geom_point(size=3) + theme_classic() + 
  scale_color_manual(values=c("cyan3", "brown1"), name=NULL, labels = c("Other chr", "chr 19")) +
  scale_shape_manual(values=c(2, 8), name=NULL, labels = c("Other chr", "chr 19")) +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_discrete(labels = c( "avg_mut" = expression(mu %->% pi),
                               "c1*c7" = expression(r %->% mu %->% pi),
                               "c2*c6" = expression(r %->% B %->% pi),
                               "B" = expression(B %->% pi),
                               "prop_del_sites" = expression(E %->% pi),
                               "covar" = expression(mu %~% E))) +
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  labs(title=NULL, x="Path", y="Coefficient") +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=14), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_PC_DAG4_1Mb.pdf", p4, base_height=6, base_width=14)

t1 <- ggplot(data=filter(chr_params_ext, op=="~~", DAG==4, !is.na(constrained_model)), 
             aes(x=chrom, y=est, alpha=sig)) +
  geom_point(size=3) + geom_hline(yintercept=0, linetype="dashed") +
  facet_grid(scale/1e3~constrained_model, labeller=labeller(constrained_model=model_labels)) + 
  scale_y_continuous(breaks=pretty_breaks()) + theme_classic() + 
  scale_x_continuous(breaks=1:num_chrom) + 
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  labs(title=NULL, x="Chromosome", y=expression(Cov(mu, E))) +
  theme(strip.text.y=element_text(size=16),    
        strip.text.x=element_text(size=16),       
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_cov_mut_E.pdf", t1, base_height=7, base_width=15)

#################
#
# Why do some chr fit better than others? 
#
#################

summary(chr_fitmeasures_latent)
summars <- fread("~/Data/bgs_lmr/human_data/data/h38.genome")
names(summars)[1] <- "chrom"

# reloading
human_maps_10kb <- fread("maps/maps_10kb.csv.gz") %>% filter(., constrained_model %in% constrained_models) %>% setDT()
human_maps_100kb <- fread("maps/maps_100kb.csv.gz") %>% filter(., constrained_model %in% constrained_models) %>% setDT()
human_maps_1Mb <- fread("maps/maps_1Mb.csv.gz") %>% filter(., constrained_model %in% constrained_models) %>% setDT()

# mutation latent
mut_latent_10kb <- fread("maps/mut_latent_10kb.csv.gz")
mut_latent_100kb <- fread("maps/mut_latent_100kb.csv.gz")
mut_latent_1Mb <- fread("maps/mut_latent_1Mb.csv.gz")

# B-map latent
B_latent_10kb <- data.frame()
B_latent_100kb <- data.frame()
B_latent_1Mb <- data.frame()

for(m in constrained_models) {
  
  tmp_10kb<- fread(paste0("maps/B_latent_", m, "_10kb.csv.gz"))
  tmp_100kb <- fread(paste0("maps/B_latent_", m, "_100kb.csv.gz"))
  tmp_1Mb <- fread(paste0("maps/B_latent_", m, "_1Mb.csv.gz"))
  
  B_latent_10kb <- rbind.data.frame(B_latent_10kb, tmp_10kb)
  B_latent_100kb <- rbind.data.frame(B_latent_100kb, tmp_100kb)
  B_latent_1Mb <- rbind.data.frame(B_latent_1Mb, tmp_1Mb)
}

# merging per chr summaries
## 10 kb 
tbl_10kb <- left_join(filter(human_maps_10kb, mut_map=="roulette"),
                      mut_latent_10kb, by=c("chrom", "chromStart", "chromEnd"))
tbl_10kb[, rec_latent_log := log1p(avg_rec)] # no latent for rec, use log of raw pyrho instead

tbl_10kb <- filter(tbl_10kb, coverage >= 0.75) %>%
  dplyr::select(., c(chrom,
                     constrained_model,
                     prop_del_sites,
                     rec_latent_log, 
                     mut_latent_log)) %>%
  group_by(., chrom, constrained_model) %>%
  mutate(prop_del_sites_log=log1p(prop_del_sites)) %>%
  summarize_at(vars(mut_latent_log, rec_latent_log, prop_del_sites_log), .funs=mean, na.rm=TRUE) 
tbl_10kb <- left_join(tbl_10kb, summars, by="chrom") %>% setDT()

tbl_10kb$scale <- 1e4
tbl_10kb$constrained_model <- factor(tbl_10kb$constrained_model, 
                                levels = names(elem_labels), 
                                labels = unname(elem_labels)) 

## 100 kb 
tbl_100kb <- left_join(human_maps_100kb, mut_latent_100kb, by=c("chrom", "chromStart", "chromEnd"))
tbl_100kb[, rec_latent_log := log1p(avg_rec)] # no latent for rec, use log of raw pyrho instead

tbl_100kb <- filter(tbl_100kb, coverage >= 0.5) %>%
  dplyr::select(., c(chrom,
                     constrained_model,
                     prop_del_sites,
                     rec_latent_log, 
                     mut_latent_log)) %>%
  group_by(., chrom, constrained_model) %>%
  mutate(prop_del_sites_log=log1p(prop_del_sites)) %>%
  summarize_at(vars(mut_latent_log, rec_latent_log, prop_del_sites_log), .funs=mean, na.rm=TRUE) 
tbl_100kb <- left_join(tbl_100kb, summars, by="chrom") %>% setDT()

tbl_100kb$scale <- 1e5
tbl_100kb$constrained_model <- factor(tbl_100kb$constrained_model, 
                                     levels = names(elem_labels), 
                                     labels = unname(elem_labels)) 

## 1 Mb 
tbl_1Mb <- left_join(human_maps_1Mb, mut_latent_1Mb, by=c("chrom", "chromStart", "chromEnd"))
tbl_1Mb[, rec_latent_log := log1p(avg_rec)] # no latent for rec, use log of raw pyrho instead

tbl_1Mb <- filter(tbl_1Mb, coverage >= 0.25) %>%
  dplyr::select(., c(chrom,
                     constrained_model,
                     prop_del_sites,
                     rec_latent_log, 
                     mut_latent_log)) %>%
  group_by(., chrom, constrained_model) %>%
  mutate(prop_del_sites_log=log1p(prop_del_sites)) %>%
  summarize_at(vars(mut_latent_log, rec_latent_log, prop_del_sites_log), .funs=mean, na.rm=TRUE) 
tbl_1Mb <- left_join(tbl_1Mb, summars, by="chrom") %>% setDT()

tbl_1Mb$scale <- 1e6
tbl_1Mb$constrained_model <- factor(tbl_1Mb$constrained_model, 
                                      levels = names(elem_labels), 
                                      labels = unname(elem_labels)) 

tbl_summaries <- rbind.data.frame(tbl_10kb, tbl_100kb, tbl_1Mb)
df <- left_join(tbl_summaries, chr_fitmeasures_latent, by=c("scale", "chrom", "constrained_model"))

# diagnostics
p <- ggplot(data=df, aes(x=GC, y=cfi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), vjust=2, size=3) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="GC %", y="CFI") +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_CFI_GC.pdf", p, base_height=8, base_width=14)

q <- ggplot(data=df, aes(x=mut_latent_log, y=cfi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), vjust=2, size=3) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Log Mut. Latent", y="CFI") +
  theme(strip.text.y=element_text(size=16),  
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_CFI_Mut.pdf", q, base_height=8, base_width=14)

r <- ggplot(data=df, aes(x=rec_latent_log, y=cfi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), vjust=2, size=3) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Log Rec. Latent", y="CFI") +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_CFI_Rec.pdf", r, base_height=8, base_width=14)

s <- ggplot(data=df, aes(x=prop_del_sites_log * 100, y=cfi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), vjust=2, size=3) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="% Del. Sites", y="CFI") +
  theme(strip.text.y=element_text(size=16),     
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_CFI_delsites.pdf", s, base_height=8, base_width=14)

setDT(chr_r2_dags)
tab <- left_join(tbl_summaries, chr_r2_dags, by=c("scale", "chrom", "constrained_model"))

lm_list <- list(length=length(constrained_models) * length(unique(tab$scale)) * length(unique(tab$DAG)))
pos <- 1
for(const in unique(tab$constrained_model)) {
  for(scal in unique(tab$scale)) {
    for(dag in unique(tab$DAG)) {
      
      df_transf <- filter(tab, constrained_model==const, scale==scal, DAG==dag) %>%
        dplyr::select(., c(avg_pi, prop_del_sites_log, mut_latent_log, rec_latent_log, GC)) %>% setDT()
      
      df_transf <- apply(df_transf, 2, std_by_sd) %>% as.data.frame()
      setnames(df_transf, old=c("mut_latent_log", "rec_latent_log", "prop_del_sites_log"),
                          new=c("avg_mut", "avg_rec", "prop_del_sites"))
      
      meta_lm <- lm(data=df_transf, formula=avg_pi ~ GC + prop_del_sites + avg_mut + avg_rec)
      
      summ <- summary(meta_lm)
      
      coefs_df <- as.data.frame(summ$coefficients)
      coefs_df$term <- rownames(coefs_df)
      rownames(coefs_df) <- NULL
      names(coefs_df)[4] <- "p-value"
      
      coefs_df$constrained_model <- const
      coefs_df$scale <- scal
      coefs_df$DAG <- dag
      coefs_df$r2_lm <- summ$r.squared
      coefs_df$r2_adj_lm <- summ$adj.r.squared
      
      lm_list[[pos]] <- coefs_df %>% dplyr::select(., c("term", "Estimate", "p-value",
                                                      "constrained_model", "scale", "DAG", 
                                                      "r2_lm", "r2_adj_lm")) %>% filter(., term!="(Intercept)")
      pos <- pos + 1
    }
  }
}

coefs_df <- data.table::rbindlist(lm_list)
fwrite(setDT(coefs_df), paste("sem/obspi_lm_r2pi.csv", sep=""))

coefs_df$sig <- coefs_df$`p-value` < 0.05

n <- ggplot(data=filter(coefs_df, DAG==3 | DAG==4), 
            aes(x=term, y=Estimate, alpha=sig, color=as.factor(DAG))) +
  geom_point(size=3.5) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_x_discrete(labels=c("avg_mut"=expression(mu),
                            "avg_rec"="r",
                            "GC"="GC",
                            "prop_del_sites"="E")) +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.35), 
                     labels=c("TRUE"="Significant", "FALSE"="Non-Significant"), name=NULL) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Feature", y="Linear Coefficient") +
  theme(strip.text.y=element_text(size=16),
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=18), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/lm_chr_featrures_r2pi.pdf", n, base_height=8, base_width=14)

names(coefs_df)[7] <- "R-sqrd"
names(coefs_df)[8] <- "R-sqrd.adjusted"

r2_df <- filter(coefs_df, term=="GC") %>% pivot_longer(., cols=starts_with("R"), names_to="r2")

o <- ggplot(data=filter(r2_df, DAG==3 | DAG==4, r2=="R-sqrd.adjusted"), 
            aes(x=scale / 1e3, y=value * 100, color=as.factor(DAG))) +
  geom_point(size=3.5, shape=16) +
  facet_wrap(~constrained_model) + theme_classic() + 
  scale_x_log10(breaks=c(10, 100, 1000)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Scale (kb)", y="Var. Explained (%)") +
  theme(strip.text=element_text(size=16), 
        axis.title=element_text(size=16), 
        axis.text=element_text(size=16), 
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/r2r2_pi.pdf", o, base_height=5, base_width=8)

p <- ggplot(data=filter(tab, DAG==3 | DAG==4), 
            aes(x=GC, y=avg_pi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), size=4) +
  geom_smooth(method="lm", se=FALSE) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="GC %", y=expression(R^2)) +
  theme(strip.text.y=element_text(size=16),       
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_R2_GC.pdf", p, base_height=8, base_width=12)

q <- ggplot(data=filter(tab, DAG==3 | DAG==4), 
            aes(x=mut_latent_log, y=avg_pi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), size=3) +
  geom_smooth(method="lm", se=FALSE) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_shape_manual(values=c(0, 1), name="Method") +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x="Scaled Mutation Latent", y=expression(R^2)) +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_R2_Mut.pdf", q, base_height=8, base_width=12)

r <- ggplot(data=filter(tab, DAG==3 | DAG==4), 
            aes(x=rec_latent_log, y=avg_pi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), size=3) +
  geom_smooth(method="lm", se=FALSE) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x=expression(log(1+italic(r))), y=expression(R^2)) +
  theme(strip.text.y=element_text(size=16),      
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_R2_Rec.pdf", r, base_height=8, base_width=12)

s <- ggplot(data=filter(tab, DAG==3 | DAG==4), 
            aes(x=prop_del_sites_log, y=avg_pi, color=as.factor(DAG))) +
  geom_text(aes(label=chrom), size=3) +
  geom_smooth(method="lm", se=FALSE) +
  facet_grid(scale/1e3~constrained_model) + theme_classic() + 
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_color_manual(values=c("brown1", "cyan3"), name="DAG") +
  labs(title=NULL, x=expression(log(1+italic(E))), y=expression(R^2)) +
  theme(strip.text.y=element_text(size=16),
        strip.text.x=element_text(size=16),
        axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")
save_plot("sem/chr_R2_delsites.pdf", s, base_height=8, base_width=12)


###################
#
# Tables
#
####################

LRT_gw_freechrom <- vector("list", length=12)
c <- 1
for(d in 1:4) {
  for(m in constrained_models) {
    tmp <- fread(paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_10kb_latents_", m, ".csv"))
    tmp <- cbind.data.frame(tmp$`Pr(>Chisq)`[2], m, d, 1e4)
    names(tmp) <- c("pvalue", "elements", "DAG", "scale")
    
    LRT_gw_freechrom[[c]] <- tmp
    c <- c + 1
  }
}
tbl_LRT_gw_freechrom_10kb <- data.table::rbindlist(LRT_gw_freechrom)

LRT_gw_freechrom <- vector("list", length=12)
c <- 1
for(d in 1:4) {
  for(m in constrained_models) {
    tmp <- fread(paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_100kb_latents_", m, ".csv"))
    tmp <- cbind.data.frame(tmp$`Pr(>Chisq)`[2], m, d, 1e5)
    names(tmp) <- c("pvalue", "elements", "DAG", "scale")
    
    LRT_gw_freechrom[[c]] <- tmp
    c <- c + 1
  }
}
tbl_LRT_gw_freechrom_100kb <- data.table::rbindlist(LRT_gw_freechrom)

LRT_gw_freechrom <- vector("list", length=12)
c <- 1
for(d in 1:4) {
  for(m in constrained_models) {
    tmp <- fread(paste0("sem/lavaan_out/obspi_LRT_DAG", d, "_gw-equal-freechrom_1Mb_latents_", m, ".csv"))
    tmp <- cbind.data.frame(tmp$`Pr(>Chisq)`[2], m, d, 1e6)
    names(tmp) <- c("pvalue", "elements", "DAG", "scale")
    
    LRT_gw_freechrom[[c]] <- tmp
    c <- c + 1
  }
}
tbl_LRT_gw_freechrom_1Mb <- data.table::rbindlist(LRT_gw_freechrom)

tbl_LRT_gw_freechrom <- rbind.data.frame(tbl_LRT_gw_freechrom_10kb, tbl_LRT_gw_freechrom_100kb, tbl_LRT_gw_freechrom_1Mb)
fwrite(tbl_LRT_gw_freechrom, "sem/LRT_gw_freechrom_models.csv")

