# Configuration for Snakemake
# Paths are relative to bgs_lmr/tools

# Paths to large input data
roulette_vcf_dir: "../data/roulette_vcfs/"
gvcf_dir: "/media/nick/Elements/Data/NYGC_hg38/gvcfs/"

# Paths to large intermediate data
allele_count_dir: "/media/nick/Elements/Data/NYGC_hg38/allele_count_arrays/"

# Sample IDs
sample_id_file: "../config/YRI_sample_ids.txt"

# Define models
demogs:
  - "equilibrium_granular_Ne"
  - "equilibrium_single_Ne"

mut_models:
  - "carlson"
  - "gnomad"
  - "roulette"

cons_models:
  - "merged_cds_regulatory"
  - "split_cds_regulatory"
  - "merged_cds_phastcons"
  - "split_cds_phastcons"

# Define for which models we should create fine-scale B maps

fine_map_demogs: ["equilibrium_granular_Ne"]
fine_map_mut_models: ["roulette"]
fine_map_cons_models: 
  - "split_cds_regulatory"
  - "split_cds_phastcons"
